### ISSUE TITLE
构建结果未导出 TS 定义

### ISSUE THREAD

**Issue by dream2023** [dongggcom/wangeditor-for-react#11]
如下图所示，当 TS 项目使用时，会一片红。

![image](https://user-images.githubusercontent.com/19297757/126645695-a296d92a-a199-4691-b07e-73abbe848f91.png)

建议使用 [father-build](https://github.com/umijs/father) 可以轻易构建出想要的结果，并支持 typescript。

**Comment by dream2023** [comment]
作者有时间搞一下吗

**Comment by dongggcom** [comment]
> 作者有时间搞一下吗

不好意思，最近忙一些个人的事情没关注邮件，我记下了，近期看一下。

**Comment by dongggcom** [comment]
更新至 1.5.1
