### ISSUE TITLE
props value 好像没有效果

### ISSUE THREAD

**Issue by yangfanzn** [dongggcom/wangeditor-for-react#14]
value这个props, 好像没有作用呀? 看了源码, 确实没有发现有使用的地方
请问这个value有什么作用吗???
我想改变editor的内容, 必须使用ref吗??

**Comment by qq1052504303** [comment]
同时使用defaultValue和value属性即可实现受控

**Comment by Tiamokeke** [comment]
> 同时使用defaultValue和value属性即可实现受控

并没有用啊

**Comment by dongggcom** [comment]
可以理解为异步处理数据 ，onchange 触发的更新会及时同步到状态上，只是不需要回传给 wangeditor-for-react，value 这个属性我还没有很好的处理，所以暂时没有写到文档中。
