### ISSUE TITLE
请问如何disable和enable

### ISSUE THREAD

**Issue by chenqingxiao007** [dongggcom/wangeditor-for-react#18]
React版本并未暴露方法
private readonly id;
    private hasCreated;
    protected imgFile: ImgFile;
    protected defaultConfig: Record<string, unknown>;
    editor: WEdtior | null;
    componentDidUpdate(nextProps: ReactWEProps): void;
    componentDidMount(): void;
    componentWillUnmount(): void;
    private __hook__run;
    private __before__instanced;
    private __after__instanced;
    protected init(): void;
    protected check(): boolean;
    protected create(context?: {}): void;
    extend(context?: Record<string, unknown>, customFilter?: string[]): void;
    destroy(): void;
    setConfig(config: Record<string, unknown> | undefined): void;
    setDefaultConfigByProps: () => void;
    setContentByHTMLString(html: string | undefined): void;
    replaceHTMLImgBlobURL(html: string, callback: (v: File | {
        toString: () => string;
    }) => string): string;
    render(): React.ReactElement;
    changeCreatedFlag: (flag: boolean) => boolean;
    created: () => boolean;
    destroyed: () => boolean;
    isCreated: () => boolean;

**Comment by dongggcom** [comment]
可以用`ref`获取 `editor` 后，直接使用` editor` 的 `API`
