### ISSUE TITLE
粘贴过滤问题

### ISSUE THREAD

**Issue by Chocolate1999** [dongggcom/wangeditor-for-react#21]
![image](https://user-images.githubusercontent.com/61035508/147455844-d5a7080b-f15f-42f4-886d-8a04e287939d.png)

![image](https://user-images.githubusercontent.com/61035508/147456060-c27f6e3e-dae8-4b39-80a7-96bf4e371446.png)

文档中说是配置都是默认的，即 

 - 会默认过滤掉复制文本的样式

使用的是 chrome 浏览器，在 React 中添加了配置项没有效果
 ```
pasteFilterStyle: true,
```

下面的一点 `忽略粘贴内容中的图片` 配置了也没有效果

**Comment by dongggcom** [comment]
贴一下你配置都代码

**Comment by Chocolate1999** [comment]
> 贴一下你配置都代码

感谢大佬的回复，如下是配置，pasteFilterStyle: true

```

xxx

const editorConfig: any = {
        menus: ['image'],
        showFullScreen: false,
        customUploadImg: handleCustomUploadImg,
        onchange: handleOnChange,
        showLinkImg: false,
        height: 135,
        showMenuTooltips: false,
        placeholder: placeholder,
        pasteFilterStyle: true, // add
   };
return (
        <>
            <ReactWEditor
                ref={editorRef}
                config={editorConfig}
            />
        </>
    );


```

**Comment by dongggcom** [comment]
我看了下 wangeditor 的实现，主要是处理标签中的 style 属性，一些默认的标签带来的样式没法避免。
