### ISSUE TITLE
bug:1.5.4版本，打包有错误。

### ISSUE THREAD

**Issue by stan900814** [dongggcom/wangeditor-for-react#24]
![微信图片_20220301122507](https://user-images.githubusercontent.com/24645404/156104779-53831429-d450-43b9-9119-12a99a6ac8be.png)

**Comment by ping0815** [comment]
请问怎么解决呢

**Comment by 18335130244** [comment]
有解决吗？

**Comment by 18335130244** [comment]
最终还是 降级到 1.5.3 使用吧

**Comment by dongggcom** [comment]
我先check 一下，最近休假了没关注。

**Comment by dongggcom** [comment]
1.5.4 就将 react 依赖移出了，防止内部多版本 react , 我猜你们是没有安装 react 导致的吧？

**Comment by dongggcom** [comment]
1.5.5
