### ISSUE TITLE
回显时，设置value值  再次编辑 回车后 光变 返回上一行

### ISSUE THREAD

**Issue by Yancy-Yeung** [dongggcom/wangeditor-for-react#30]
如题，1.5.3 版本；一旦 使用 value 值 用作 回显，onChange 编辑 时 ，按 回车键 ，就会 自动 返回 上一行；
如果 不用 onChange ，改用 onBlur ，直接 按 下方 update 来 axios ，光标没 能 onblur；数据 没能实现 更新；通过 按钮事件想把 focus 来 转移 光标 实现 onBlur 事件，却 又发现 ，光标 不肯 离开

**Comment by dongggcom** [comment]
是不是设置 value 了？可以不用回填
