### ISSUE TITLE
表格外框线样式没获取到

### ISSUE THREAD

**Issue by zhaigang2333** [dongggcom/wangeditor-for-react#4]
对比了下与编辑器展示的样式是一样的，但是展示到其他html就是没有外框线，麻烦看看，谢谢
<img width="1057" alt="QQ20210512-224439@2x" src="https://user-images.githubusercontent.com/25580637/117995144-ab363700-b373-11eb-964a-7cc6ae392451.png">

**Comment by dongggcom** [comment]
请参考：[官方文档](https://doc.wangeditor.com/pages/02-%E5%86%85%E5%AE%B9%E5%A4%84%E7%90%86/03-%E8%8E%B7%E5%8F%96html.html)
