### ISSUE TITLE
怎么在create之前自定义扩展菜单？

### ISSUE THREAD

**Issue by ZililuYa** [dongggcom/wangeditor-for-react#5]
怎么在create之前自定义扩展菜单？
求助！！
const editor = new E('#div1')
// 注册菜单
editor.menus.extend(menuKey, AlertMenu)

// 将菜单加入到 editor.config.menus 中    const menuKey = 'alertMenuKey' 
// 也可以通过配置 menus 调整菜单的顺序，参考【配置菜单】部分的文档    editor.config.menus.push(menuKey)
editor.config.menus = editor.config.menus.concat(menuKey)

// 注册完菜单，再创建编辑器，顺序很重要！！
editor.create()

**Comment by dongggcom** [comment]
参考下官方文档：[自定义菜单](https://www.wangeditor.com/doc/pages/03-%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95/01-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95.html)

**Comment by ZililuYa** [comment]
> 参考下官方文档：[自定义菜单](https://www.wangeditor.com/doc/pages/03-%E9%85%8D%E7%BD%AE%E8%8F%9C%E5%8D%95/01-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8F%9C%E5%8D%95.html)

我看过文档好多次了
你发的这个是自定义菜单（是已经存在的菜单）
我想要的是自定义扩展菜单
目前create是在组件内完成的
引用即完成，但是wangEditor的自定义扩展菜单需要在create之前创建，所以我感到困惑，不知道怎么写，希望作者可以修改一下
@dongggcom 
[自定义扩展菜单](https://www.wangeditor.com/doc/pages/11-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E8%8F%9C%E5%8D%95/01-%E5%BF%AB%E9%80%9F%E6%89%A9%E5%B1%95%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95.html)

**Comment by dongggcom** [comment]
感谢提问，1.4.0版本增加了 hook 的支持。 [hook](https://github.com/dongggcom/wangeditor-for-react#%E5%A2%9E%E5%8A%A0-hook)
