### ISSUE TITLE
赋值value和onChange，回车会回到上一个光标的位置

### ISSUE THREAD

**Issue by chen-jieyi** [dongggcom/wangeditor-for-react#7]
![image](https://user-images.githubusercontent.com/35585258/123392601-d0070680-d5cf-11eb-8bc2-1a28e7dadb18.png)

**Comment by dongggcom** [comment]
在新的 1.4.1 版本修复了这个问题。更新下哈。

**Comment by yangmin4052** [comment]
1.5.3还有这个问题

**Comment by Tiamokeke** [comment]
> 1.5.3还有这个问题

同样遇到了这个问题
