### ISSUE TITLE
扩展菜单时候，那些组件继承是官方的 wangeditor ？

### ISSUE THREAD

**Issue by shenqihui** [dongggcom/wangeditor-for-react#9]
import E from 'wangeditor';

const { BtnMenu } = E
class AlertMenu extends BtnMenu {
}

感觉怪怪的，为啥不直接使用 `wangeditor-for-react` 能导出一个。

**Comment by dongggcom** [comment]
很好的想法，不过暂时不提供更新。
wangeditor-for-react 的职责主要是提供 react 版本的支持，使用 wangeditor 的引用只强调了来自 wangeditor，未来如果可能有 AnyComponent 的话，这种写法会更合适。

**Comment by shenqihui** [comment]
主要是太奇怪了，package 安装 wangeditor-for-react ，但是内部自动依赖 wangeditor 会不需要加进package。
这时候js明确引用 wangeditor ，感觉还是得加到 package 里面明确依赖。

只是像表达这样用起来怪怪的，没啥其他。
